### ISSUE TITLE
Training label value outside the valid range

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#11]
I'm trying to train 3 classes of one crop on one single stacked images with Band2, Band3, Band4 and Band8. I could run till the step "Creating a model for training", I also passed "--nclasses 3" as an input parameter. The command I used is as follows: 
`sudo docker run -u otbuser -w="/home/otbuser/" -v $(pwd):/home/otbuser mdl4eo/otbtf1.7:gpu python /home/otbuser/OTB_DeepLearn/otbtf_GPU/python/create_savedmodel_simple_cnn.py --nclasses 3 --outdir /home/otbuser/Deep_Learning_Examples/Output/4.Model_for_Training
`
  
But when I tried to train the model I received error as mentioned below.  
_"Received a label value of 3 which is outside the valid range of [0, 3)"_ 
Any suggestion what might be wrong..?

The command that I used for training the model:
`sudo docker run -u otbuser -w="/home/otbuser/" -v $(pwd):/home/otbuser mdl4eo/otbtf1.7:gpu otbcli_TensorflowModelTrain -model.dir /home/otbuser/Deep_Learning_Examples/Output/4.Model_for_Training -training.targetnodes optimizer -training.source1.il /home/otbuser/Deep_Learning_Examples/Output/3.Patch_Extraction/March2_samp_patches_16X16.tif -training.source1.patchsizex 16 -training.source1.patchsizey 16 -training.source1.placeholder x -training.source2.il /home/otbuser/Deep_Learning_Examples/Output/3.Patch_Extraction/March2_samp_patches_labels.tif -training.source2.patchsizex 1 -training.source2.patchsizey 1 -training.source2.placeholder y -model.saveto /home/otbuser/Deep_Learning_Examples/Output/4.Model_for_Training/variables/variables`  

![Screenshot from 2019-10-18 03-01-11](https://user-images.githubusercontent.com/28738918/67045734-13517680-f159-11e9-9eec-1459230d17b6.png)

**Comment by remicres** [comment]
Hi, 
your classes values must start from 0.
3 classes ==> [0,2]

**Comment by Pratyush1991** [comment]
Thank you so much.
