### ISSUE TITLE
Fused conv implementation does not support grouped convolutions

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#13]
Hello,
I stacked 11 tif files (each with 4 bands) together to one single tif which contains 44 bands in total. When I try to train the model with 7 classes it gives an error as  "Unimplemented: Fused conv implementation does not support grouped convolutions for now  [{{node conv2d/Relu}}]]" . Can you suggest what might be the problem.?

![Screenshot from 2019-10-20 02-51-10](https://user-images.githubusercontent.com/28738918/67150656-8a674600-f2e4-11e9-9cb0-bda251118df4.png)

**Comment by remicres** [comment]
The problem comes from your model. If you post the python code used to generate the SavedModel, I can help. Have you updated it to take in account properly the 44 channels ? (in particular, the placeholder definition)

**Comment by Pratyush1991** [comment]
Hello,
Yeah as you mentioned, I didn't change the placeholder definition while generating saved model. I did update it to account for 44 channels. I only change the changed the 'x' placeholder definition to 44 which was 4 earlier. It worked and I could produce an output map.
Thank you again.

**Comment by Raevel** [comment]
Sorry, i'm new to this and didn't understand the solution. Getting same error. Could you explain it a little more?

What did you changed in your code to make this work?

**Comment by Pratyush1991** [comment]
> Sorry, I'm new to this and didn't understand the solution. Getting the same error. Could you explain it a little more?
> 
> What did you change in your code to make this work?

Hello,
You should change the value of the placeholder x to the number of bands that you have for the image (by default it is 4). In my case, I changed the value from 4 to 44.
Example Line 52 in Simple CNN model: 
https://github.com/remicres/otbtf/blob/3daef29fa0a741497d47abc13b83829434ae511f/python/create_savedmodel_simple_cnn.py#L52
