### ISSUE TITLE
Cannot find application ImageTimeSeriesGapFilling inside OTBTF Docker build

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#14]
Hello,

I wanted to apply Time Series Gap filling for the Sentinel2 images as I have masked the areas with cloud cover. But the application isn't available. I did check the OTB documents it says the application is available for OTB version 7.0.0 (which is same as OTBTF docker build). So I logged in to the docker image (mdl4eo/otbtf1.7:gpu) to check if it was available or not, I couldn't find the application under bin folder of otb superbuild (Image attached below). I wonder why is it not present. I found similar issue (link attached below) but not sure if it is related to this issue or not. [Link] ((http://otb-users.37221.n3.nabble.com/Issues-with-remote-module-application-loading-td4028832.html))

Regards,
Pratyush

![Screenshot from 2019-11-03 01-36-54](https://user-images.githubusercontent.com/28738918/68075441-86eeb700-fdda-11e9-844a-005b599566e1.png)

![Screenshot from 2019-11-03 01-31-36](https://user-images.githubusercontent.com/28738918/68075389-b51fc700-fdd9-11e9-9990-70a0bf38dcf9.png)

**Comment by remicres** [comment]
Gapfilling is not compiled in the image.
You can compile it simply with:

```
cd /work/otb/build/OTB/build
cmake /work/otb/otb -DModule_OTBTemporalGapFilling=ON
make install
otbcli_ImageTimeSeriesGapFilling -help
```
