### ISSUE TITLE
how to change the OTB_TF_NSOURCES

### ISSUE THREAD

**Issue by radhiachrt** [remicres/otbtf#15]
Hi, I couldn't change the variable OTB_TF_NSOURCES with this command:
$ sudo docker run -u otbuser -v $(pwd):/home/otbuser otbtf_image  export OTB_TF_NSOURCES=2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"export\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled 
Which is the right way.
Thank you

**Comment by remicres** [comment]
Related to docker. To set an environment variable using the `docker run` command you can use `-e` (or `--env`).
Source: https://docs.docker.com/engine/reference/commandline/run/

**Comment by radhiachrt** [comment]
Thank you, it works.
$ sudo docker run  -e  OTB_TF_NSOURCES=2 -u  otbuser -v $(pwd):/home/otbuser otbtf_image
