### ISSUE TITLE
Semantic segmentation

### ISSUE THREAD

**Issue by lolob** [remicres/otbtf#19]
Hi,
I hope everyone is doing well #stayhome.
After completing the tutorial on "patch-based", I'm trying to go for semantic segmentation. I notice that there's already an example on [semantic segmentation](https://github.com/remicres/otbtf_tutorials_resources) . I guess it is a Unet form. By looking at the codes, probably the input patches is 64x64x4. So, I just use the PatchesExtraction application and create both sets for 'training' and 'validation', right?

**Comment by remicres** [comment]
Hi, yes it is! Just create you patches locations, then extract them (use `OTB_TF_NSOURCES=2` to extract patches jointly in label image and satellite image). Hint: Airbus provides free Spot 7 samples for the Amsterdam area ;)
Somedy has to write a tutorial about this :innocent:

**Comment by lolob** [comment]
Thanks @remicres. Will come again with another question 👍
