### ISSUE TITLE
Which pixel represents the sampling point for patches extracted when the size is 16*16.? (even numbers)

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#22]
Hello, 

I'm a bit confused regarding the patch extraction for the sampling point generated. Correct me if I'm wrong, As far as I have understood that the sampling point is the center pixel and the patches extracted are spatial extent which respect to the center pixel. 
So if the patch size is 5x5 then the center pixel (sampling point) would be (2,2) right.?  If the patch size is odd then I can understand which would be the center pixel. But what if the patch size is even let say 16x16 or 8x8 then which pixel represents the center pixel (sampling point).?

**Comment by remicres** [comment]
Hi,

> So if the patch size is 5x5 then the center pixel (sampling point) would be (2,2) right.?

Yes.

![image](https://user-images.githubusercontent.com/6161755/82143105-a82c6780-9841-11ea-892f-5b501e86c0dc.png)

_Center of a 7x7 patch_

>  But what if the patch size is even let say 16x16 or 8x8

In otbtf, the convention is to use the first pixel next to the actual patch center (i.e. where physical index is **greater or equal** the actual center). So, the first available 16x16 patch in an image starts from 0, has a size of 16: its center index is (8,8). 

![image](https://user-images.githubusercontent.com/6161755/82143140-de69e700-9841-11ea-864e-8862bf9d414b.png)

_Center of a 8x8 patch (crs origin: top left)_

**Comment by Pratyush1991** [comment]
@remicres Got it. Thank you
