### ISSUE TITLE
PTX JIT Compiler Library not found

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#24]
Hello, 

As Windows Subsystem Linux (WSL2) with the recent update is able to use GPU on Windows 10. (https://forums.fast.ai/t/platform-windows-10-using-wsl2-w-gpu/73521). So I did try to install the otbtf2.0:gpu on Windows 10 with WSL2 on Ubuntu 18.04 LTS. The installation was successful. But while training the model I got an error as PTX JIT Compiler Library not found. 
I'm not sure is it because of the Linux Kernel used in WSL2 .? As I see that it shows a message as "Your Kernel may have been built without NUMA support". And also Is it possible to compile PTX JIT Compiler Library?

Regards,
Pratyush 

![image](https://user-images.githubusercontent.com/28738918/86067799-e30bf700-ba9f-11ea-9028-92202b7b0953.png)

![image](https://user-images.githubusercontent.com/28738918/86066912-a808c400-ba9d-11ea-814a-dcd90feeddf7.png)

**Comment by Pratyush1991** [comment]
Looks like it is a limitation for WSL2 for the current release. https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations. 

However, I did try to install otbtf2.0:cpu and train the model.  But the otbcli_TensorflowModelTrain module doesn't work. It shows error as "Illegal instruction".

![image](https://user-images.githubusercontent.com/28738918/86103442-f8f0da80-bae6-11ea-91ef-58e74e89baf4.png)

Then I tried installing otbtf1.7:gpu . It did work and it could access GPU during model training.  As otbtf 1.7 works on WSL2 with GPU support so I'm not sure why with otbtf2.0 it shows PTX JIT compiler error.


![image](https://user-images.githubusercontent.com/28738918/86154934-ed74d200-bb2d-11ea-85f9-ec0fbb529dbf.png)

**Comment by remicres** [comment]
Thanks for the feedback.
Regarding the otbtf2.0-gpu issue: your link points to a current limitation of CUDA 11 on WSL2. I guess that TF2.X comes by default with PTX JIT. Maybe one could try to rebuilt the docker without xla/jit? Don't know if possible. I believe XLA is already disabled in the docker image.

Regarding the otbtf2.0:cpu issue, my guess is that it is related to intel MKL. What is your CPU? Same workaround here for now, one could rebuild the docker without the MKL support, disabling the options [here](https://github.com/remicres/otbtf/blob/master/tools/dockerfiles/r2.0/bionic.tf-r2.1.otb-7.1/Dockerfile#L114) and [here](https://github.com/remicres/otbtf/blob/master/tools/dockerfiles/r2.0/bionic.tf-r2.1.otb-7.1/Dockerfile#L115)

**Comment by Pratyush1991** [comment]
Maybe I will try to build TF2.X first on a fresh Docker image and check if it works. Cause I see the example shown in https://docs.nvidia.com/cuda/wsl-user-guide/index.html#running-dlfw uses TF2.1.0 with CUDA on WSL2.

The CPU in which I tried otbtf2.0cpu is Intel i7 9th Gen. Maybe I will try to build without MKL support. But at present, I'm happy with otbtf1.7:gpu :)

**Comment by Pratyush1991** [comment]
Hello @remicres ,

So I rebuild the Tensorflow with gpu inside the docker image otbtf2.0:gpu and it worked. There two things that I changed:

1. Before configuring Tensorflow, I added some path to LD_LIBRARY_PATH
`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64/:/usr/local/cuda/lib64/stubs/"`
(by default the path is /usr/local/nvidia/lib:/usr/local/nvidia/lib64)

2. Enabled xla/jit while configuring the TensorFlow in otbtf2.0:gpu.
`export TF_ENABLE_XLA=1`

Thank you for your suggestions.

Regards,
Pratyush

**Comment by remicres** [comment]
Hi @Pratyush1991 that's great. Could you make a PR on `develop` branch?

**Comment by Pratyush1991** [comment]
> Hi @Pratyush1991 that's great. Could you make a PR on `develop` branch?

Yeah, I have made one PR.  Let me know if it is okay.

**Comment by remicres** [comment]
That is great! I will run a few tests with this new docker image. If it works with both WSL2 and Linux systems, I think that this one will replace the otbtb2.0 on dockerhub. Thanks!

**Comment by remicres** [comment]
Just updated the dockerfile thank to your corrections. I also updated the docker image on dockerhub. Thanks again

**Comment by Pratyush1991** [comment]
You are welcome. I'm glad I could contribute. :) I'll close this issue then
