### ISSUE TITLE
Support for Tensorboard

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#26]
Hello @remicres ,

Just wanted to know if it is possible to view the model training on Tensorboard using TensorflowModelTraining.? I think it can be done if I don't use Otbtf so training, but at the same time, the classification results from TensorflowModelTraining (precision, recall, and fscore) is also something that I want to see during training as well.

**Comment by remicres** [comment]
Hi @Pratyush1991 ,
I didn't start to develop this feature for now! I agree that this could be very useful.
