### ISSUE TITLE
can't reach Tensorflow-dependent APPS with docker

### ISSUE THREAD

**Issue by kh039426** [remicres/otbtf#29]
operating system: windows 10 pro
docker image: mdl4eo/otbtf2.0:cpu

command: 
D:\yuchen\OTB-7.1.0-Win64\data_set>docker run -u otbuser -v "%cd%":/home/otbuser mdl4eo/otbtf2.0:cpu otbcli_TensorflowModelTrain

Illegal instruction

same problem with apps such as:
TensorflowModelServe
TrainClassifierFromDeepFeatures
ImageClassifierFromDeepFeatures

**Comment by remicres** [comment]
Hi @kh039426 ,
I just updated the docker image on dockerhub.
Can you give a new try?

**Comment by kh039426** [comment]
Hi @remicres 

I can reach the function now. thank you for help
