### ISSUE TITLE
OTB build Centos

### ISSUE THREAD

**Issue by resnow92** [remicres/otbtf#5]
Hi,
I have some difficulties to build OTB from sources with my Centos 7 machine.
I followed all institutions --> 
`cmake  -D CMAKE_INSTALL_PREFIX=~/OTB/install ../otb/SuperBuild` command was succcefull:

**output :**
`-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OTB version : 6.6.0
-- CMake build type is none. Setting it to Release
-- Environment setup for Configure (SB_ENV_CONFIGURE_CMD): env;CC=/usr/bin/cc;CXX=/usr/bin/c++
-- Environment setup for CMake (SB_CMAKE_COMMAND) : env;CC=/usr/bin/cc;CXX=/usr/bin/c++;/usr/local/bin/cmake;-GUnix Makefiles
-- |----------------------------------------------------------
-- |----------------- System checkup results -----------------
-- | The following libraries have been found on your system.
-- | You can choose to use them (instead of superbuild versions)
-- | by setting the corresponding option USE_SYSTEM_XXX.
-- |----------------------------------------------------------
-- | CURL	(7.29.0) 	: /usr/lib64/libcurl.so
-- |----------------------------------------------------------
-- | GDAL	(1.11.2) 	: /home/s_admin/anaconda2/lib/libgdal.so
-- |----------------------------------------------------------
-- | ITK	(4.12.0) 	: /usr/lib/cmake/ITK-4.12
-- |----------------------------------------------------------
-- Custom patches required for TIFF
-- Custom patches required for PNG
-- Custom patches required for PROJ
-- Custom patches required for GEOS
-- Custom patches required for HDF4
-- Custom patches required for NETCDF
-- Custom patches required for GDAL
-- Custom patches required for OSSIM
-- Custom patches required for ITK
-- Custom patches required for BOOST
-- Custom patches required for SHARK
-- Custom patches required for MUPARSERX
-- Custom patches required for QT5
-- Custom patches required for GLEW
-- Custom patches required for GLFW
-- Custom patches required for QWT
-- Using system version of SWIG
-- Using SuperBuild version of BOOST
-- Using SuperBuild version of CURL
-- Using SuperBuild version of EXPAT
-- Using SuperBuild version of FFTW
-- Using SuperBuild version of FREETYPE
-- Using SuperBuild version of GDAL
-- Using SuperBuild version of GEOS
-- Using SuperBuild version of GEOTIFF
-- Using SuperBuild version of GLEW
-- Using SuperBuild version of GLFW
-- Using SuperBuild version of GLUT
-- Using SuperBuild version of GSL
-- Using SuperBuild version of HDF4
-- Using SuperBuild version of HDF5
-- Using SuperBuild version of ITK
-- Using SuperBuild version of JPEG
-- Using SuperBuild version of LIBKML
-- Using SuperBuild version of LIBSVM
-- Using SuperBuild version of MUPARSER
-- Using SuperBuild version of MUPARSERX
-- Using SuperBuild version of NETCDF
-- Using SuperBuild version of OPENCV
-- Using SuperBuild version of OPENJPEG
-- Using SuperBuild version of OPENSSL
-- Using SuperBuild version of OPENTHREADS
-- Using SuperBuild version of OSSIM
-- Using SuperBuild version of OTB
-- Using SuperBuild version of PNG
-- Using SuperBuild version of PROJ
-- Using SuperBuild version of QT5
-- Using SuperBuild version of QWT
-- Using SuperBuild version of SHARK
-- Using SuperBuild version of SQLITE
-- Using SuperBuild version of TIFF
-- Using SuperBuild version of TINYXML
-- Using SuperBuild version of ZLIB
-- OTB_TARGET_SYSTEM_ARCH=x86_64
-- OTB_TARGET_SYSTEM_ARCH_IS_X64=TRUE
-- DOWNLOAD_LOCATION is not set. We will download all source archives during build!
-- SuperBuild will be installed to /home/s_admin/OTB/install
-- To install to a different directory, re-run cmake -DCMAKE_INSTALL_PREFIX=/your/preferred/path
-- Configuring done
-- Generating done
-- Build files have been written to: /home/s_admin/OTB/build`

But the "make" command give me this error:

`
[s_admin@l-sentinel-dev build]$ make
[  1%] Performing download step (download, verify and extract) for 'GLUT'
CMake Error at GLUT-stamp/GLUT-download-Release.cmake:16 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/s_admin/OTB/build/GLUT/src/GLUT-stamp/GLUT-download-Release-impl.cmake'

  See also

    /home/s_admin/OTB/build/GLUT/src/GLUT-stamp/GLUT-download-*.log

make[2]: *** [GLUT/src/GLUT-stamp/GLUT-download] Error 1
make[1]: *** [CMakeFiles/GLUT.dir/all] Error 2
make: *** [all] Error 2

`

I don't know how to solve this I don't understand the error.

Thanks for yout help.

**Comment by remicres** [comment]
You must look in the log file mentioned (/home/s_admin/OTB/build/GLUT/src/GLUT-stamp/GLUT-download-err.log) 

It seems related to the download of glut.

If you don't need all the gui stuff, I recommand to disable glut, glew, opengl, qt,...
