### ISSUE TITLE
Dockerfile build failed on Centos 7

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#6]
Hello,

Currently I'm trying to build the docker file on Centos 7 machine. I am getting error for the building step for SWIG. 

Any suggestion would be helpful. 

Regards,
Pratyush

![Screenshot from 2019-08-11 00-27-17](https://user-images.githubusercontent.com/28738918/62825016-267f1d80-bbcf-11e9-97b9-dd8fed0f0f0e.png)

**Comment by remicres** [comment]
Can you copy paste here the content of the file mentioned in the error message ?

**Comment by Pratyush1991** [comment]
I logged in into the docker image and searched for the log file path i.e
/work/otb/build/SWIG/src/SWIG-stamp/SWIG-build-*.log

But I cannot find the folder 'otb' inside 'work' folder. The only folder inside the work folder is 'tf'. 
I wonder if this is the right path where I am supposed to look for the log file or is it because the build wasn't successful the folder doesn't exist ?

![Screenshot from 2019-08-14 14-08-25](https://user-images.githubusercontent.com/28738918/63001948-f40b4400-be9e-11e9-8503-79ec395396e1.png)

**Comment by remicres** [comment]
Indeed, since docker fails at the otb step, its state is the previous one: only tf is built.
Can you enter the docker in interactive mode, and run manually the commands of the otb step? (i.e. from [here](https://github.com/remicres/otbtf/blob/954b6951f6be1c3560c0cfd35b351008499fc79b/tools/dockerfiles/bionic.tf-r1.14.otb-develop/Dockerfile#L131))
Then you will be able to copy/paste the error log

**Comment by Pratyush1991** [comment]
As you mentioned. I did try manually. The output of the SWIG-build-err log file is attached below. 
I says yacc command is missing.   

![Screenshot from 2019-08-14 15-47-37](https://user-images.githubusercontent.com/28738918/63007821-93363880-beab-11e9-8c07-a8a4d2bb672e.png)

**Comment by remicres** [comment]
can you try to install the "bison" package? just do `apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends bison`

Then try again?

**Comment by Pratyush1991** [comment]
Thank you so much. I added the "bison" package to the docker file and build the image again.  It is successfully installed now. 

But for the usage part I am not sure how to use. I just used the sample command that you posted in the docker file. But that gives an error as "no matching entries in password file".

![Screenshot from 2019-08-14 23-43-24](https://user-images.githubusercontent.com/28738918/63039990-acaca400-beee-11e9-8026-c33ac6048881.png)

**Comment by remicres** [comment]
I've modified the Dockerfile.
Bison package is now installed, and usage instructions have been modified.
Please close this issue if Dockerfile build is OK on Centos 7, and feel free to open another one if there is still some issues with the usage.
Thanks
