### ISSUE TITLE
No more "import gdal" when >= 3.3

### ISSUE THREAD

**Issue by vidlb** [remicres/otbtf#71]
File gdal.py file was removed in GDAL 3.3 :
```
Traceback (most recent call last):
  File "./python/otbtf.py", line 31, in <module>
    import gdal
ModuleNotFoundError: No module named 'gdal'
```
As in old GDAL releases, it is required to use
```python
from osgeo import gdal
```
It is backward compatible.

Not a problem when using Ubuntu's 20.04 default GDAL release (as in Dockerfile), but 3.3 is now default in most distrib (OTB Superbuild, future Ubuntu LTS...), or when using  ubuntu-gis PPA.

**Comment by remicres** [comment]
fixed in Release 3.2.1
