### ISSUE TITLE
ERROR: Failed to open GDALDataset file *.gpkg

### ISSUE THREAD

**Issue by HardRock4Life** [remicres/otbtf#73]
Hello! I’m trying to do an image segmentation using OTBTF.

Configuration setup:
- Windows10
- Docker Image mdl4eo/otbtf3.0:cpu-basic
- QGIS version: 3.16.8

When I’m rasterizing a *.gpkg vector layer, it says:
Rasterization: itk::ERROR: Failed to open GDALDataset file buildings_.gpkg : disk I/O error: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory.

What might be causing the problem?

**Comment by remicres** [comment]
Hi @HardRock4Life ,

Looks GDAL/OGR related.
Maybe that is because the .gpkg must not be opened elsewhere.
I believe that you have to remove it from the QGIS layers before trying to play with it.

Hope that helps.

**Comment by HardRock4Life** [comment]
True, that really worked!
Thank you 👍
