### ISSUE TITLE
illegals instruction (core dumped)

### ISSUE THREAD

**Issue by farissetiawan6** [remicres/otbtf#77]
i am using otbtf2.5:cpu on ubuntu 18.04. 
But in using the **otbcli_TensorflowModelTrain** command there is an error that is **illegals instruction (core dumped)**. I need help
![e](https://user-images.githubusercontent.com/99633837/155686110-b3600345-35bd-439e-b587-cb913d26dc3e.PNG)

**Comment by remicres** [comment]
Hi @farissetiawan6 

This is likely because your computer does not support some of the CPU flags which have been used to build the docker image.
Can give a try with the `cpu-basic` docker image?

**Comment by farissetiawan6** [comment]
it worked, thank you
