### ISSUE TITLE
Error training

### ISSUE THREAD

**Issue by farissetiawan6** [remicres/otbtf#82]
I have a problem. I want to use CNN using the VARI vegetation index. but there are obstacles like this. I need help
(https://user-images.githubusercontent.com/99633837/172090459-0eda8b44-ede2-4685-8e18-f25e985024e0.PNG)

**Comment by remicres** [comment]
Did you look at #13 ?

**Comment by farissetiawan6** [comment]
thanks very much. very helpful and successful

**Comment by remicres** [comment]
Hi, I don't know, you probably have no validation sample.
