### ISSUE TITLE
Update docker's sudo package to fix: sudo: setrlimit(RLIMIT_STACK): Operation not permitted 

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#86]
Hello @remicres ,

While using the docker, if any command is typed with sudo it prints this message:  `sudo: setrlimit(RLIMIT_STACK): Operation not permitted`. Although it has no effect as it seems like a warning. But updating the sudo package fixes this issue.

```
wget https://www.sudo.ws/dist/sudo.tar.gz
tar -zxvf sudo.tar.gz
cd sudo-1.9.11p3/
sudo su
./configure --prefix=/usr --libexecdir=/usr/lib --with-secure-path --with-all-insults --with-env-editor --docdir=/usr/share/doc/sudo-1.9.5p2 --with-passprompt="[sudo] password for %p: "
make -j 
make install && ln -sfv libsudo_util.so.0.0.0 /usr/lib/sudo/libsudo_util.so.0`
```
https://clay-atlas.com/us/blog/2021/02/09/linux-en-how-to-upgrade-sudo/ 

Will it be possible to update this in docker as well.?

**Comment by remicres** [comment]
Hi @Pratyush1991

The new otbtf release is on its way (images should be available in a few hours)
I guess the sudo package will be up to date

**Comment by Pratyush1991** [comment]
Hello @remicres ,

Thanks for the update. I checked in the latest GPU docker as well. The message still appears. I guess updating the base image from Ubuntu20.04 to Ubuntu22.04 might fix it.

But anyways this is just a warning from sudo package that doesn't have any effect on OTB or OTBTF and anyone who wants to fix can follow the above method.  

I will close this issue for now.
