### ISSUE TITLE
Can't run the tensorflow session 

### ISSUE THREAD

**Issue by yahcut** [remicres/otbtf#87]
Hi @remicres 

I follow the tutorial from your book for simple cnn case. Everything work fine, but when I train the learning model, then the error message come:
(FATAL) TensorflowModelTrain: itk::ERROR: TensorflowMultisourceModelTrain(0x5567085fa830): Can't run the tensorflow session !
[tf_error.txt](https://github.com/remicres/otbtf/files/9228243/tf_error.txt)

I used the docker image version mdl4eo/otbtf:3.1-gpu-opt-dev

My computer spec is:
![spec_pc](https://user-images.githubusercontent.com/110327071/182015604-bb351330-1fba-4cef-be29-431585e69c10.PNG)

I have tried to find it online about the problem but I have no clue. Please help me. Thank you.

**Comment by nicolasnn** [comment]
Have you tried decreasing the batch size ? By default, `training.batchsize` is 100

**Comment by remicres** [comment]
@yahcut looks like a oom issue as @nicolasnn pointed out

**Comment by yahcut** [comment]
@nicolasnn and @remicres 
Thank you very much for your response. I am so sorry for being late in responding. 

Yes, it works by decreasing the training.batchsize
