### ISSUE TITLE
OTBTF Multiarch Docker images (aarch64) 

### ISSUE THREAD

**Issue by daspk04** [remicres/otbtf#94]
Hi @remicres !

Recently I was trying to build otbtf images for aarch64 but it wasn't successful. The problem was [libinsighttoolkit4-dev](https://github.com/remicres/otbtf/blob/346dba88238a15d5e78789b2cfe21b499663c46f/tools/docker/build-deps-cli.txt#L38) wasn't available, so I wanted to just confirm do you think is it somehow still possible to build image for aarch64 .?

References : 
- https://medium.com/nttlabs/buildx-multiarch-2c6c2df00ca2  
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by remicres** [comment]
Hi @Pratyush1991 , in theory you can build ITK4 from sources. I used to do that long time ago before we have the SuperBuild, and I remember that it was quite smooth. But I never tried on aarch64

**Comment by remicres** [comment]
I don't have any pointer to build it from source, sorry. But I believe the process is quite straightforward with CMake.

**Comment by daspk04** [comment]
Hi @remicres !

Just to update I was also able to build OTB for aarch64 using Nix in [Github action](https://github.com/daspk04/otb-nix/actions/runs/10183451261/job/28168405490). At-least for now it seems to build fine. 

[Reference that I used for nix](https://thewagner.net/blog/2023/11/20/building-nix-packages-for-the-raspberry-pi-with-github-actions/)

**Comment by daspk04** [comment]
Hi @remicres !

I have added remote modules for OTBTF only the TensorFlow independent apps. [c.f](https://github.com/daspk04/otb-nix/pull/15).  I still need to spend some time to check how to build TensorFlow from source using Nix possibly next month.

Meanwhile I have some questions related to remote packages regarding the LICENSE. Currently the remote modules are optional and are not enabled by default in the [Nix-pkgs](https://github.com/daspk04/otb-nix/blob/fcd35141b3725c63cea2343ee948ce52f4aecb88/pkgs/otb/default.nix#L34). As you are the author for most of the remote modules that I have added to [OTB Nix-Pkgs](https://github.com/daspk04/otb-nix/blob/fcd35141b3725c63cea2343ee948ce52f4aecb88/pkgs/otb/default.nix#L62), if you could check [this comment](https://github.com/daspk04/otb-nix/pull/15#issuecomment-2312718129) and provide any suggestion or any feedback would be nice! 

I'll close this issue as this has been resolved by me [here](https://github.com/daspk04/otb-nix/pull/15)
